services:
  catalogdb:    
    container_name: shopping-mongo
    ports:
      - 27017:27017 
    volumes:
       -  "shopping-mongo:/data/db"
  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8000:8080"
    depends_on: 
      - catalogdb
